import { Lab, Material, Concept, Constraint, Decision } from '@/types';
import { generateDefaultConstraints } from './constraint-engine';

export const AUTHENTIC_ATELIER_MATERIALS: Material[] = [
  {
    id: 'MAT-001',
    label: 'Raw Indigo Selvedge Denim Roll',
    category: 'denim',
    form: 'roll',
    visual: {
      dominant_color: 'Deep Indigo',
      secondary_colors: ['Natural Ecru', 'Copper Stitching'],
      pattern: 'Twill Weave with Redline Selvedge ID',
      texture_cues: 'Crisp, structured, 3x1 right-hand twill',
      swatch_hex: '#1E293B',
    },
    estimate: {
      visible_dimensions: '42" width × approx 4.8 yards',
      piece_count: 1,
      quantity_estimate: {
        value: 4.8,
        unit: 'yards',
        confidence: 0.94,
      },
    },
    properties: {
      stretch_guess: 'Rigid zero-stretch (visual cue suggests 100% shuttle-loom cotton)',
      opacity_guess: 'Opaque 100%',
      weight_class_guess: 'Heavyweight ~13.5 oz (450 GSM)',
    },
    provenance: {
      source_image: 'https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=800&q=80',
      capture_time: '2026-09-12T10:14:00Z',
      user_notes: 'Salvaged from North Carolina denim mill surplus lot.',
    },
    confidence: 0.94,
    verification: 'verified',
    approved: true,
    locked: true,
  },
  {
    id: 'MAT-002',
    label: 'Mulberry Raw Silk Organza Remnant',
    category: 'silk',
    form: 'panel',
    visual: {
      dominant_color: 'Ivory Pearl',
      secondary_colors: ['Warm Cream'],
      pattern: 'Semi-sheer plain weave with organic slubs',
      texture_cues: 'Paper-crisp hand, sheer luster, subtle drape memory',
      swatch_hex: '#F8F6F0',
    },
    estimate: {
      visible_dimensions: '36" × 58" irregular cut',
      piece_count: 2,
      quantity_estimate: {
        value: 2.2,
        unit: 'meters',
        confidence: 0.88,
      },
    },
    properties: {
      stretch_guess: 'Non-stretch (visual cue suggests pure filament silk organza)',
      opacity_guess: 'Semi-sheer (~35% opacity)',
      weight_class_guess: 'Ultra-lightweight ~42 GSM',
    },
    provenance: {
      source_image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=80',
      capture_time: '2026-09-12T10:14:22Z',
      user_notes: 'Bridal cutting table end-roll remnant.',
    },
    confidence: 0.88,
    verification: 'verified',
    approved: true,
    locked: false,
  },
  {
    id: 'MAT-003',
    label: 'Terracotta 8-Wale Corduroy Panel',
    category: 'corduroy',
    form: 'panel',
    visual: {
      dominant_color: 'Terracotta Rust',
      secondary_colors: ['Burnt Sienna'],
      pattern: 'Prominent 8-wale ribbed cut velvet ridge',
      texture_cues: 'Plush velvet pile, soft tactile ribs',
      swatch_hex: '#C85A32',
    },
    estimate: {
      visible_dimensions: '44" × 72"',
      piece_count: 1,
      quantity_estimate: {
        value: 1.8,
        unit: 'meters',
        confidence: 0.91,
      },
    },
    properties: {
      stretch_guess: 'Low mechanical cross-grain give (visual cue suggests cotton corduroy)',
      opacity_guess: 'Opaque 100%',
      weight_class_guess: 'Medium-heavy ~310 GSM',
    },
    provenance: {
      source_image: 'https://images.unsplash.com/photo-1607344645866-009c320b5ab8?auto=format&fit=crop&w=800&q=80',
      capture_time: '2026-09-12T10:15:05Z',
      user_notes: 'Overstock upholstery bolt sample.',
    },
    confidence: 0.91,
    verification: 'verified',
    approved: true,
    locked: false,
  },
  {
    id: 'MAT-004',
    label: 'Burgundy Silk Duchesse Satin Scrap',
    category: 'silk',
    form: 'scrap',
    visual: {
      dominant_color: 'Deep Burgundy',
      secondary_colors: ['Ruby Red Sheen', 'Wine'],
      pattern: 'High-luster satin weave with fluid drape',
      texture_cues: 'Liquid-smooth surface, sculptural body',
      swatch_hex: '#6B1728',
    },
    estimate: {
      visible_dimensions: '28" × 34" triangular taper',
      piece_count: 2,
      quantity_estimate: {
        value: 0.9,
        unit: 'meters',
        confidence: 0.86,
      },
    },
    properties: {
      stretch_guess: 'Bias stretch only (visual cue suggests heavy woven duchesse satin)',
      opacity_guess: 'Opaque 100%',
      weight_class_guess: 'Medium weight ~210 GSM',
    },
    provenance: {
      source_image: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=800&q=80',
      capture_time: '2026-09-12T10:15:40Z',
      user_notes: 'Gown offcut scrap lot.',
    },
    confidence: 0.86,
    verification: 'needs_review',
    approved: true,
    locked: false,
  },
  {
    id: 'MAT-005',
    label: 'Olive Drab Weathered Canvas Remnant',
    category: 'cotton',
    form: 'panel',
    visual: {
      dominant_color: 'Olive Drab',
      secondary_colors: ['Field Tan', 'Khaki'],
      pattern: 'Dense duck plain weave with patina',
      texture_cues: 'Brushed wax touch, robust structure',
      swatch_hex: '#4D583F',
    },
    estimate: {
      visible_dimensions: '48" × 80"',
      piece_count: 1,
      quantity_estimate: {
        value: 2.8,
        unit: 'meters',
        confidence: 0.93,
      },
    },
    properties: {
      stretch_guess: 'Zero stretch (visual cue suggests heavy military-spec duck canvas)',
      opacity_guess: 'Opaque 100%',
      weight_class_guess: 'Heavyweight ~360 GSM',
    },
    provenance: {
      source_image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=800&q=80',
      capture_time: '2026-09-12T10:16:15Z',
      user_notes: 'Vintage tent fabric repurposing stock.',
    },
    confidence: 0.93,
    verification: 'verified',
    approved: true,
    locked: false,
  },
  {
    id: 'MAT-006',
    label: 'Reclaimed Antique Brass Heavy Zippers (4x)',
    category: 'hardware',
    form: 'trim',
    visual: {
      dominant_color: 'Antique Brass',
      secondary_colors: ['Dark Charcoal Tape'],
      pattern: '#10 Metal Tooth chunky teeth',
      texture_cues: 'Cast metal teeth on reinforced polyester twill tape',
      swatch_hex: '#A38047',
    },
    estimate: {
      visible_dimensions: 'Two 24" separating, two 9" pocket zips',
      piece_count: 4,
      quantity_estimate: {
        value: 4,
        unit: 'pieces',
        confidence: 0.97,
      },
    },
    properties: {
      stretch_guess: 'Rigid teeth on tape',
      opacity_guess: 'N/A Hardware',
      weight_class_guess: 'Heavy metal hardware',
    },
    provenance: {
      source_image: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80',
      capture_time: '2026-09-12T10:16:45Z',
      user_notes: 'Outerwear production overrun hardware bin.',
    },
    confidence: 0.97,
    verification: 'locked',
    approved: true,
    locked: true,
  },
  {
    id: 'MAT-007',
    label: 'Deadstock Charcoal Ribbed Wool Trim',
    category: 'knit',
    form: 'trim',
    visual: {
      dominant_color: 'Charcoal Melange',
      secondary_colors: ['Heather Slate'],
      pattern: '2x2 Chunky Rib Knit Ribbing Strip',
      texture_cues: 'Soft merino-blend hand, resilient recovery',
      swatch_hex: '#2B2D31',
    },
    estimate: {
      visible_dimensions: '4" width × 48" tubular knit length',
      piece_count: 1,
      quantity_estimate: {
        value: 1.2,
        unit: 'meters',
        confidence: 0.89,
      },
    },
    properties: {
      stretch_guess: 'High elasticity ~65% recovery (visual cue suggests wool elastane blend)',
      opacity_guess: 'Opaque knit',
      weight_class_guess: 'Medium-heavy knit ~350 GSM',
    },
    provenance: {
      source_image: 'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?auto=format&fit=crop&w=800&q=80',
      capture_time: '2026-09-12T10:17:10Z',
      user_notes: 'Knitwear sampling offcut strip.',
    },
    confidence: 0.89,
    verification: 'verified',
    approved: true,
    locked: false,
  },
];

export const ACTIVE_CAPSULE_CONCEPTS: Concept[] = [
  {
    id: 'LOOK-01',
    look_number: 1,
    title: 'The Selvedge Modular Work Kimono',
    silhouette: 'Relaxed Drop-Shoulder Haori with Ribbed Trim & Brass Closure',
    description:
      'A structured hybrid outerwear silhouette constructed from the 13.5oz indigo selvedge roll. The visible selvedge ticker lines the center-front placket and cuffs, while the reclaimed charcoal knit forms an ergonomic neck collar band.',
    visual_uri: 'https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?auto=format&fit=crop&w=1000&q=80',
    uses: ['MAT-001', 'MAT-007', 'MAT-006'],
    material_map: [
      {
        zone: 'Main Torso & Kimono Sleeves',
        material_id: 'MAT-001',
        material_label: 'Raw Indigo Selvedge Denim Roll',
        usage_note: 'Main structural body; cut on straight grain using 2.1 yards.',
      },
      {
        zone: 'Banded Collar & Cuffs',
        material_id: 'MAT-007',
        material_label: 'Deadstock Charcoal Ribbed Wool Trim',
        usage_note: 'Ribbed contour collar for skin-comfort and warmth.',
      },
      {
        zone: 'Chest Modular Flap Fastener',
        material_id: 'MAT-006',
        material_label: 'Reclaimed Antique Brass Heavy Zippers',
        usage_note: 'Single 9" brass zipper utilized for modular chest stash pocket.',
      },
    ],
    feasibility: 'feasible',
    warnings: [],
    version: 1,
    affected: false,
    approved: true,
  },
  {
    id: 'LOOK-02',
    look_number: 2,
    title: 'Architectural Corduroy & Satin Blouson',
    silhouette: 'Cropped High-Collar Blouson with Fluid Lantern Sleeve Contrast',
    description:
      'High-contrast textural study juxtaposing the plush matte structure of the 8-wale terracotta corduroy against the high-gloss fluid drape of the burgundy duchesse satin offcut on the articulated lantern sleeves.',
    visual_uri: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1000&q=80',
    uses: ['MAT-003', 'MAT-004', 'MAT-006'],
    material_map: [
      {
        zone: 'Fitted Bodice & Stand Collar',
        material_id: 'MAT-003',
        material_label: 'Terracotta 8-Wale Corduroy Panel',
        usage_note: 'Panels cut vertically along corduroy wales for architectural stiffness.',
      },
      {
        zone: 'Pleated Lantern Sleeve Gussets',
        material_id: 'MAT-004',
        material_label: 'Burgundy Silk Duchesse Satin Scrap',
        usage_note: 'Bias-cut drape inserts providing fluid motion contrast.',
      },
      {
        zone: 'Exposed Asymmetric Center Front Zip',
        material_id: 'MAT-006',
        material_label: 'Reclaimed Antique Brass Heavy Zippers',
        usage_note: 'Full 24" separating heavy brass zipper.',
      },
    ],
    feasibility: 'feasible',
    warnings: [],
    version: 1,
    affected: false,
    approved: false,
  },
  {
    id: 'LOOK-03',
    look_number: 3,
    title: 'Deconstructed Column Duster with Sheer Inset',
    silhouette: 'Architectural Floor-Length Trench with Sheer Organza Back Vent',
    description:
      'Industrial utility duster engineered from the olive drab weathered canvas remnant. A breathability vent along the scapula is backed with the ivory raw silk organza, creating a surprising poetic translucency against military duck cloth.',
    visual_uri: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&w=1000&q=80',
    uses: ['MAT-005', 'MAT-002', 'MAT-001'],
    material_map: [
      {
        zone: 'Outer Duster Shell & Epaulettes',
        material_id: 'MAT-005',
        material_label: 'Olive Drab Weathered Canvas Remnant',
        usage_note: '2.4m utilized for main weather-resistant outer body.',
      },
      {
        zone: 'Pleated Back Yoke Inset & Vent',
        material_id: 'MAT-002',
        material_label: 'Mulberry Raw Silk Organza Remnant',
        usage_note: '1.2m silk organza layered as floating spine vent.',
      },
      {
        zone: 'Faced Storm Flaps & Belt Loop Facing',
        material_id: 'MAT-001',
        material_label: 'Raw Indigo Selvedge Denim Roll',
        usage_note: 'Denim selvedge scrap utilized for heavy-wear internal belt loops.',
      },
    ],
    feasibility: 'feasible',
    warnings: [],
    version: 1,
    affected: false,
    approved: true,
  },
];

export const CO_DESIGN_DECISION_LOG: Decision[] = [
  {
    id: 'DEC-001',
    speaker_id: 'USR-HOST',
    speaker_name: 'Sathvik (Lead Upcycler)',
    speaker_role: 'Atelier Lead',
    speaker_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=120&q=80',
    timestamp: '10:18:20 AM',
    event_type: 'material_locked',
    payload: { material_id: 'MAT-001' },
    resulting_changes: 'Locked Raw Indigo Selvedge Denim (4.8 yds) as foundational shell inventory.',
  },
  {
    id: 'DEC-002',
    speaker_id: 'USR-GUEST',
    speaker_name: 'Elena Rostova',
    speaker_role: 'Senior Patternmaker',
    speaker_avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=120&q=80',
    timestamp: '10:19:05 AM',
    event_type: 'concept_approved',
    payload: { concept_id: 'LOOK-01' },
    resulting_changes: 'Approved Look 01 (Selvedge Work Kimono) for initial prototype sample cut.',
  },
  {
    id: 'DEC-003',
    speaker_id: 'USR-HOST',
    speaker_name: 'Sathvik (Lead Upcycler)',
    speaker_role: 'Atelier Lead',
    speaker_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=120&q=80',
    timestamp: '10:20:12 AM',
    event_type: 'brief_updated',
    payload: { brief: '3 bespoke evening looks, unisex, strict circularity zero virgin fabric' },
    resulting_changes: 'Constraint updated: Zero Virgin Yardage rule promoted to Hard constraint.',
  },
];

export const PRIMARY_ATELIER_WORKSPACE: Lab = {
  id: 'lab-atelier-001',
  name: 'Deadstock Atelier Capsule #01',
  brief: '3 directional looks, unisex utility meets evening, zero virgin yardage, 100% deadstock traceability',
  audience: 'Unisex Contemporary / Circular Runway',
  occasion: 'Trans-seasonal Evening Utility',
  target_looks: 3,
  created_at: '2026-09-12T10:00:00Z',
  owner_id: 'designer-sathvik',
  status: 'active_studio',
  materials: AUTHENTIC_ATELIER_MATERIALS,
  constraints: generateDefaultConstraints('3 looks, unisex utility, zero new fabric', 3),
  concepts: ACTIVE_CAPSULE_CONCEPTS,
  decisions: CO_DESIGN_DECISION_LOG,
};

